//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class TouchTriggerWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(TouchTrigger), typeof(UnityEngine.MonoBehaviour));
		L.RegFunction("setLuaCallback", setLuaCallback);
		L.RegFunction("setLuaDoubleClick", setLuaDoubleClick);
		L.RegFunction("setParamStyle", setParamStyle);
		L.RegFunction("setIsSwallow", setIsSwallow);
		L.RegFunction("setTouchEnabled", setTouchEnabled);
		L.RegFunction("OnPointerClick", OnPointerClick);
		L.RegFunction("OnPointerDown", OnPointerDown);
		L.RegFunction("OnPointerUp", OnPointerUp);
		L.RegFunction("OnDestory", OnDestory);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int setLuaCallback(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 3)
			{
				TouchTrigger obj = (TouchTrigger)ToLua.CheckObject<TouchTrigger>(L, 1);
				LuaFunction arg0 = ToLua.CheckLuaFunction(L, 2);
				object arg1 = ToLua.ToVarObject(L, 3);
				obj.setLuaCallback(arg0, arg1);
				return 0;
			}
			else if (count == 4)
			{
				TouchTrigger obj = (TouchTrigger)ToLua.CheckObject<TouchTrigger>(L, 1);
				LuaFunction arg0 = ToLua.CheckLuaFunction(L, 2);
				object arg1 = ToLua.ToVarObject(L, 3);
				LuaFunction arg2 = ToLua.CheckLuaFunction(L, 4);
				obj.setLuaCallback(arg0, arg1, arg2);
				return 0;
			}
			else if (count == 5)
			{
				TouchTrigger obj = (TouchTrigger)ToLua.CheckObject<TouchTrigger>(L, 1);
				LuaFunction arg0 = ToLua.CheckLuaFunction(L, 2);
				object arg1 = ToLua.ToVarObject(L, 3);
				LuaFunction arg2 = ToLua.CheckLuaFunction(L, 4);
				LuaFunction arg3 = ToLua.CheckLuaFunction(L, 5);
				obj.setLuaCallback(arg0, arg1, arg2, arg3);
				return 0;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: TouchTrigger.setLuaCallback");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int setLuaDoubleClick(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			TouchTrigger obj = (TouchTrigger)ToLua.CheckObject<TouchTrigger>(L, 1);
			LuaFunction arg0 = ToLua.CheckLuaFunction(L, 2);
			object arg1 = ToLua.ToVarObject(L, 3);
			obj.setLuaDoubleClick(arg0, arg1);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int setParamStyle(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			TouchTrigger obj = (TouchTrigger)ToLua.CheckObject<TouchTrigger>(L, 1);
			int arg0 = (int)LuaDLL.luaL_checknumber(L, 2);
			obj.setParamStyle(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int setIsSwallow(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			TouchTrigger obj = (TouchTrigger)ToLua.CheckObject<TouchTrigger>(L, 1);
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			obj.setIsSwallow(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int setTouchEnabled(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			TouchTrigger obj = (TouchTrigger)ToLua.CheckObject<TouchTrigger>(L, 1);
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			obj.setTouchEnabled(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnPointerClick(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			TouchTrigger obj = (TouchTrigger)ToLua.CheckObject<TouchTrigger>(L, 1);
			UnityEngine.EventSystems.PointerEventData arg0 = (UnityEngine.EventSystems.PointerEventData)ToLua.CheckObject<UnityEngine.EventSystems.PointerEventData>(L, 2);
			obj.OnPointerClick(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnPointerDown(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			TouchTrigger obj = (TouchTrigger)ToLua.CheckObject<TouchTrigger>(L, 1);
			UnityEngine.EventSystems.PointerEventData arg0 = (UnityEngine.EventSystems.PointerEventData)ToLua.CheckObject<UnityEngine.EventSystems.PointerEventData>(L, 2);
			obj.OnPointerDown(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnPointerUp(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			TouchTrigger obj = (TouchTrigger)ToLua.CheckObject<TouchTrigger>(L, 1);
			UnityEngine.EventSystems.PointerEventData arg0 = (UnityEngine.EventSystems.PointerEventData)ToLua.CheckObject<UnityEngine.EventSystems.PointerEventData>(L, 2);
			obj.OnPointerUp(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int OnDestory(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			TouchTrigger obj = (TouchTrigger)ToLua.CheckObject<TouchTrigger>(L, 1);
			obj.OnDestory();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

