//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class UnityEngine_VerticalWrapModeWrap
{
	public static void Register(LuaState L)
	{
		L.BeginEnum(typeof(UnityEngine.VerticalWrapMode));
		L.RegVar("Truncate", get_Truncate, null);
		L.RegVar("Overflow", get_Overflow, null);
		L.RegFunction("IntToEnum", IntToEnum);
		L.EndEnum();
		TypeTraits<UnityEngine.VerticalWrapMode>.Check = CheckType;
		StackTraits<UnityEngine.VerticalWrapMode>.Push = Push;
	}

	static void Push(IntPtr L, UnityEngine.VerticalWrapMode arg)
	{
		ToLua.Push(L, arg);
	}

	static bool CheckType(IntPtr L, int pos)
	{
		return TypeChecker.CheckEnumType(typeof(UnityEngine.VerticalWrapMode), L, pos);
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Truncate(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.VerticalWrapMode.Truncate);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Overflow(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.VerticalWrapMode.Overflow);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IntToEnum(IntPtr L)
	{
		int arg0 = (int)LuaDLL.lua_tonumber(L, 1);
		UnityEngine.VerticalWrapMode o = (UnityEngine.VerticalWrapMode)arg0;
		ToLua.Push(L, o);
		return 1;
	}
}

