//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class UnityEngine_UI_Image_OriginVerticalWrap
{
	public static void Register(LuaState L)
	{
		L.BeginEnum(typeof(UnityEngine.UI.Image.OriginVertical));
		L.RegVar("Bottom", get_Bottom, null);
		L.RegVar("Top", get_Top, null);
		L.RegFunction("IntToEnum", IntToEnum);
		L.EndEnum();
		TypeTraits<UnityEngine.UI.Image.OriginVertical>.Check = CheckType;
		StackTraits<UnityEngine.UI.Image.OriginVertical>.Push = Push;
	}

	static void Push(IntPtr L, UnityEngine.UI.Image.OriginVertical arg)
	{
		ToLua.Push(L, arg);
	}

	static bool CheckType(IntPtr L, int pos)
	{
		return TypeChecker.CheckEnumType(typeof(UnityEngine.UI.Image.OriginVertical), L, pos);
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Bottom(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.UI.Image.OriginVertical.Bottom);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Top(IntPtr L)
	{
		ToLua.Push(L, UnityEngine.UI.Image.OriginVertical.Top);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IntToEnum(IntPtr L)
	{
		int arg0 = (int)LuaDLL.lua_tonumber(L, 1);
		UnityEngine.UI.Image.OriginVertical o = (UnityEngine.UI.Image.OriginVertical)arg0;
		ToLua.Push(L, o);
		return 1;
	}
}

